FROM redis:latest as builder

ENV DEPS "automake peg libtool autoconf python python-setuptools python-pip python-dev wget build-essential cmake m4 git valgrind"

# Set up a build environment
RUN set -ex;\
    deps="$DEPS";\
    apt-get update;\
    apt-get install -y --no-install-recommends $deps;\
    pip install wheel;\
    pip install Click;\
    pip install rmtest;\
    pip install git+https://github.com/RedisGraph/redisgraph-py.git@master;\
    pip install redis-py-cluster;\
    pip install backports.csv;\
    pip install psutil;\
    pip install git+https://github.com/RedisLabsModules/RLTest.git@master;\
    pip install behave

# Build the source
ADD ./ /redisgraph

# Build RedisGraph
WORKDIR /redisgraph
RUN set -ex;\
    make clean ALL=1; \
    make -j 4;
