#define OR                               1
#define AND                              2
#define EQ                               3
#define GT                               4
#define GE                               5
#define LT                               6
#define LE                               7
#define MATCH                            8
#define LEFT_PARENTHESIS                 9
#define STRING                          10
#define COLON                           11
#define RIGHT_PARENTHESIS               12
#define DASH                            13
#define LEFT_BRACKET                    14
#define RIGHT_BRACKET                   15
#define RIGHT_ARROW                     16
#define LEFT_ARROW                      17
#define WHERE                           18
#define DOT                             19
#define NE                              20
#define INTEGER                         21
#define FLOAT                           22
#define TRUE                            23
#define FALSE                           24
#define RETURN                          25
#define COMMA                           26
