#define OR                               1
#define AND                              2
#define ADD                              3
#define DASH                             4
#define MUL                              5
#define DIV                              6
#define EQ                               7
#define GT                               8
#define GE                               9
#define LT                              10
#define LE                              11
#define MATCH                           12
#define CREATE                          13
#define INDEX                           14
#define ON                              15
#define DROP                            16
#define COLON                           17
#define UQSTRING                        18
#define LEFT_PARENTHESIS                19
#define RIGHT_PARENTHESIS               20
#define SET                             21
#define COMMA                           22
#define DELETE                          23
#define RIGHT_ARROW                     24
#define LEFT_ARROW                      25
#define LEFT_BRACKET                    26
#define RIGHT_BRACKET                   27
#define LEFT_CURLY_BRACKET              28
#define RIGHT_CURLY_BRACKET             29
#define WHERE                           30
#define DOT                             31
#define RETURN                          32
#define DISTINCT                        33
#define AS                              34
#define ORDER                           35
#define BY                              36
#define ASC                             37
#define DESC                            38
#define LIMIT                           39
#define INTEGER                         40
#define NE                              41
#define STRING                          42
#define FLOAT                           43
#define TRUE                            44
#define FALSE                           45
