#define OR                               1
#define AND                              2
#define ADD                              3
#define DASH                             4
#define MUL                              5
#define DIV                              6
#define EQ                               7
#define GT                               8
#define GE                               9
#define LT                              10
#define LE                              11
#define CALL                            12
#define LEFT_PARENTHESIS                13
#define RIGHT_PARENTHESIS               14
#define YIELD                           15
#define STRING                          16
#define UQSTRING                        17
#define COMMA                           18
#define DOT                             19
#define MATCH                           20
#define CREATE                          21
#define INDEX                           22
#define ON                              23
#define DROP                            24
#define COLON                           25
#define MERGE                           26
#define SET                             27
#define DELETE                          28
#define RIGHT_ARROW                     29
#define LEFT_ARROW                      30
#define LEFT_BRACKET                    31
#define RIGHT_BRACKET                   32
#define PIPE                            33
#define INTEGER                         34
#define DOTDOT                          35
#define LEFT_CURLY_BRACKET              36
#define RIGHT_CURLY_BRACKET             37
#define WHERE                           38
#define RETURN                          39
#define DISTINCT                        40
#define AS                              41
#define WITH                            42
#define ORDER                           43
#define BY                              44
#define ASC                             45
#define DESC                            46
#define SKIP                            47
#define LIMIT                           48
#define UNWIND                          49
#define NE                              50
#define FLOAT                           51
#define TRUE                            52
#define FALSE                           53
#define NULLVAL                         54
