#define AND                              1
#define OR                               2
#define EQ                               3
#define GT                               4
#define GE                               5
#define LT                               6
#define LE                               7
#define MATCH                            8
#define LEFT_PARENTHESIS                 9
#define STRING                          10
#define COLON                           11
#define RIGHT_PARENTHESIS               12
#define DASH                            13
#define LEFT_BRACKET                    14
#define RIGHT_BRACKET                   15
#define RIGHT_ARROW                     16
#define WHERE                           17
#define DOT                             18
#define NE                              19
#define INTEGER                         20
#define FLOAT                           21
#define TRUE                            22
#define FALSE                           23
#define RETURN                          24
#define COMMA                           25
