name: Run RedisGraph Benchmarks

on:
  workflow_dispatch:
    inputs:
      extended:
        type: boolean
        description: 'Run extended benchmarks'
        default: false
  workflow_call:
    inputs:
      extended:
        type: boolean
        default: false

jobs:
  benchmark-json-oss-standalone:
    strategy:
      matrix:
        member_id: [1, 2, 3, 4, 5, 6]
    uses: ./.github/workflows/benchmark-flow.yml
    secrets: inherit
    with:
      benchmark_runner_group_member_id: ${{ matrix.member_id }}
      benchmark_runner_group_total: ${{ strategy.job-total }}


