name: Weekly Flow

on:
  schedule:
    # Every Sunday at 00:00
    - cron: "0 0 * * 0"

jobs:
  run-benchmarks:
    uses: ./.github/workflows/benchmark-runner.yml
    secrets: inherit
    with:
      extended: true
