name: Check if needs trigger CircleCI benchmark

on:
  pull_request:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  haslabel:
    name: analyse labels
    runs-on: ubuntu-latest
    outputs:
      benchmark: ${{ steps.haslabel.outputs.labeled-run-benchmark }}
    steps:
      - uses: actions/checkout@v2
      - name: Labeled with run-benchmark
        id: haslabel
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: 'run-benchmark'
  perf-ci:
    name: Trigger CI benchmarks
    needs: haslabel
    if: needs.haslabel.outputs.benchmark
    runs-on: ubuntu-latest
    steps:
      - name: trigger-circle-ci
      - uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_CI_SECRET }}
        with:
          run_default_flow: false
          run_benchmark_flow_label: true
